combo = 0
comboscore = 0
comboscoremax = 0
combominus = 0
timer_max = 1
timer = 0
title_index = 0.35
very = false
alarm[0] = 1
x = 832
y = 197
ystart = y
depth = -300
visible = hud_get_visible()
fmod_studio_event_instance_oneshot_3d("event:/sfx/misc/comboend", x, y)
