scr_getinput()
draw_set_font(global.bigfont)
draw_set_halign(fa_left)
draw_set_valign(fa_middle)
draw_set_color(c_white)
var _os = audio_select
draw_text_color(330, 100, "BACK", c_white, c_white, c_white, c_white, (_os == -1 ? 1 : 0.5))
draw_text_color(330, 175, "MASTER", c_white, c_white, c_white, c_white, (_os == 0 ? 1 : 0.5))
draw_slider(580, 175, audiosaved_master, 0)
draw_text_color(330, 250, "MUSIC", c_white, c_white, c_white, c_white, (_os == 1 ? 1 : 0.5))
draw_slider(580, 250, audiosaved_music, 1)
draw_text_color(330, 325, "SFX", c_white, c_white, c_white, c_white, (_os == 2 ? 1 : 0.5))
draw_slider(580, 325, audiosaved_sfx, 2)
