text = "THIS IS A WIP FANGAME BASED OFF EGGPLANT,\nA BUNCH OF STUFF IS MISSING\nSUCH AS SFX AND EFFECTS\nFROM THE FINAL GAME.\nCONSIDER THIS AN EARLY, EARLY\nAPPETIZER OF WHATS TO COME!"
xorigin = 1
yorigin = 0
font = global.smallfont
