draw_set_color(#fe0000)
draw_set_alpha(0.68)
draw_primitive_begin(pr_trianglelist)
var x2 = x + (32 * image_xscale)
var y2 = y + (32 * image_yscale)
draw_vertex(x, y2)
draw_vertex(x2, y2)
draw_vertex(x2, y)
draw_primitive_end()
draw_reset_color(1)
